namespace ResourceTypes.OC3.FaceFX
{
    public enum FxInputOp : uint
    {
        IO_Invalid = 0xFFFFFFFF,
        IO_Sum = 0x0,
        IO_Multiply = 0x1,
        IO_Max = 0x2,
        IO_Min = 0x3,
    }

    public enum FxLinkFnType : uint
    {
        LFT_Invalid = 0xFFFFFFFF,
        LFT_Null = 0x0,
        LFT_Linear = 0x1,
        LFT_Quadratic = 0x2,
        LFT_Cubic = 0x3,
        LFT_Sqrt = 0x4,
        LFT_Negate = 0x5,
        LFT_Inverse = 0x6,
        LFT_OneClamp = 0x7,
        LFT_Constant = 0x8,
        LFT_Corrective = 0x9,
        LFT_ClampedLinear = 0xA,
        LFT_TrueQuadratic = 0xB,
        LFT_First = 0x0,
        LFT_Last = 0xB,
        LFT_NumLinkFnTypes = 0xC,
    }

    public enum FxCompiledFaceGraphNodeType : uint
    {
        NT_Invalid = 0xFFFFFFFF,
        NT_Combiner = 0x0,
        NT_Delta = 0x1,
        NT_CurrentTime = 0x2,
        NT_GenericTarget = 0x3,
        NT_BonePose = 0x4,
        NT_MorphTarget = 0x5,
        NT_MaterialParameter = 0x6,
        NT_MaterialParameterUE3 = 0x7,
        NT_MorphTargetUE3 = 0x8,
        NT_BoneWeight = 0x9,
        NT_Attribute = 0xA,
        NT_First = 0x0,
        NT_Last = 0xA,
        NT_NumNodeTypes = 0xB,
    }

    public enum FxPhoneme : uint
    {
        PHON_INVALID = 0xFFFFFFFF,
        PHON_FIRST = 0x0,
        PHON_SIL = 0x0,
        PHON_P = 0x1,
        PHON_B = 0x2,
        PHON_T = 0x3,
        PHON_D = 0x4,
        PHON_K = 0x5,
        PHON_G = 0x6,
        PHON_M = 0x7,
        PHON_N = 0x8,
        PHON_NG = 0x9,
        PHON_RA = 0xA,
        PHON_RU = 0xB,
        PHON_FLAP = 0xC,
        PHON_PH = 0xD,
        PHON_F = 0xE,
        PHON_V = 0xF,
        PHON_TH = 0x10,
        PHON_DH = 0x11,
        PHON_S = 0x12,
        PHON_Z = 0x13,
        PHON_SH = 0x14,
        PHON_ZH = 0x15,
        PHON_CX = 0x16,
        PHON_X = 0x17,
        PHON_GH = 0x18,
        PHON_HH = 0x19,
        PHON_R = 0x1A,
        PHON_Y = 0x1B,
        PHON_L = 0x1C,
        PHON_W = 0x1D,
        PHON_H = 0x1E,
        PHON_TS = 0x1F,
        PHON_CH = 0x20,
        PHON_JH = 0x21,
        PHON_IY = 0x22,
        PHON_E = 0x23,
        PHON_EN = 0x24,
        PHON_EH = 0x25,
        PHON_A = 0x26,
        PHON_AA = 0x27,
        PHON_AAN = 0x28,
        PHON_AO = 0x29,
        PHON_AON = 0x2A,
        PHON_O = 0x2B,
        PHON_ON = 0x2C,
        PHON_UW = 0x2D,
        PHON_UY = 0x2E,
        PHON_EU = 0x2F,
        PHON_OE = 0x30,
        PHON_OEN = 0x31,
        PHON_AH = 0x32,
        PHON_IH = 0x33,
        PHON_UU = 0x34,
        PHON_UH = 0x35,
        PHON_AX = 0x36,
        PHON_UX = 0x37,
        PHON_AE = 0x38,
        PHON_ER = 0x39,
        PHON_AXR = 0x3A,
        PHON_EXR = 0x3B,
        PHON_EY = 0x3C,
        PHON_AW = 0x3D,
        PHON_AY = 0x3E,
        PHON_OY = 0x3F,
        PHON_OW = 0x40,
        PHON_OPEN = 0x41,
        PHON_LAST = 0x41,
        NUM_PHONS = 0x42,
    }
}
