name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore Mafia2Libs/MafiaToolkit.csproj
    - name: Build
      run: dotnet build Mafia2Libs/MafiaToolkit.csproj --no-restore --output "_out"
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MafiaToolkit
        path: _out
